name: Publish Maven Package
on:
  push:
    paths:
      - 'packages/**'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
      - name: Publish package
        run: |
          mkdir -p maven-repo/com/arthenica/ffmpeg-kit-audio/6.0-2/
          cp packages/ffmpeg-kit-audio-6.0-2.aar maven-repo/com/arthenica/ffmpeg-kit-audio/6.0-2/
          mvn deploy:deploy-file \
            -DgroupId=com.arthenica \
            -DartifactId=ffmpeg-kit-audio \
            -Dversion=6.0-2 \
            -Dpackaging=aar \
            -Dfile=packages/ffmpeg-kit-audio-6.0-2.aar \
            -Durl=file:./maven-repo/ \
            -DrepositoryId=github
      - name: Commit and push maven repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add maven-repo/
          git commit -m "Publish Maven package"
          git push
